import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
public class Main {

    public static void main(String[] args) throws Exception {
            //Los siguentes 3 Trytest() son para probar el try, catch y finally, el try le dara la oportunidad de realizar la operación, la idea de la operación es que solamente sea
            // de numeros positivos, en caso de que se ingrese un dato que no sea un int el programa continuara y habra hecro print del error, para continuar con los siguentes trytest
            // el finally simplemente se utiliza para avisar de que la operación y el uso de Trytest() se acabó
        //Try.Trytest();
        //Try.Trytest();
        //Try.Trytest();
            //Los throws sirven para que podamos notificar errores de una manera más personalizada y precisa para nuestro trabajo
            //ya que podemos elegir nosotros el mensaje del error para especificar donde se encuentra el error y ser más precisos en encontrarlos y arreglarlos
        //Throw.test("testing");
        //Throw.test2("testing");
        //Throw.test3(3,0);
        Throw.test4();
}
    }
